### ISSUE TITLE
What about optional `serde::Serialize` and `quote::ToTokens` impls behind feature flags

### ISSUE THREAD

**Issue by ch3pjw** [mcy/strings#5]
Would @mcy be amenable to adding `serde::Serialize` and `quote::ToTokens` trait implementations to the library gated by feature flags?

I have a library where I'm doing some serialisation and macro stuff, and it would be most useful not to have to faff with wrapper types. I appreciate that increases the surface area of the library but, at least `serde::Serialize`, is probably quite widely applicable. Adding the feature flags will keep the default build dependency free.

I'm happy to write the actual `impl`s etc if you're happy with the general idea.

**Comment by mcy** [comment]
Sorry, but that's a no. Not for technical reasons, see #1.

**Comment by ch3pjw** [comment]
From #1:
>  I also think cfgs of this type are evil, which I have been meaning to write about at some point.

Could you elaborate? In Haskell I would just implement `serde::Serialize` on your foreign type, but I believe Rust, being more conservative, doesn't have an elegant solution for this case. I've only seen either using newtype wrappers or persuading library authors to add `impl`s for you, neither of which I find hugely appealing. I've also not found `serde`'s custom (de)serialization hooks to be particularly ergonomic.

> The serde author has shown themselves to be both an irresponsible programmer and a shitty person... I do not want to endorse their work or support their ecosystem.

I read through the post you linked. I'm not sure that I find arguing against including code for political reasons instead of on technical merit is particularly strong when your complaint against the `serde` author and Rust team appears to be that they didn't include code for political reasons instead of on technical merit. However, it's your library, so...?

Thanks for the useful library and reviewing the idea anyway. Do you happen to have time to review #6?
